server:
  port: 8098
spring:
  application:
    name: aneti-service-recherche
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/aneti}
  elasticsearch:
    uris: ${ELASTICSEARCH_URI:http://localhost:9200}
    username: ${ELASTICSEARCH_USERNAME:elastic}
    password: ${ELASTICSEARCH_PASSWORD:elastic_secret}
eureka:
  client:
    service-url:
      defaultZone: http://eureka:${EUREKA_PASSWORD:eureka_secret}@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
springdoc:
  api-docs:
    path: /v3/api-docs
